# -*- coding: utf-8 -*-
"""ML_comparison.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vXzP-Uxh21_RubWB-FevxuDX05sHyHZl

##Comparing the ML algorithm
"""

import joblib
import numpy as np
from time import time
from sklearn.metrics import accuracy_score , precision_score , recall_score

dataset = np.loadtxt('./rand_heart.data', delimiter=',')
train = dataset[:,:-1]
label = dataset[:,-1]
tr_features,tst_features = np.split(train,[int(len(train)*0.8)])
tr_labels,tst_labels = np.split(label,[int(len(label)*0.8)])

names = ['LR','SVM','MLP','RF','GB']

#Testing
def evaluate_model(name,model,features,labels):
  start = time()
  pred = model.predict(features)
  end = time()
  accuracy = round(accuracy_score(labels,pred),3)
  precision = round(precision_score(labels,pred),5)
  recall = round(recall_score(labels,pred),3)
  print("{} -- accuracy: {} / precision: {} / recall: {} / Latency: {}ms".format(name,accuracy,precision,recall,round((end-start),5)))

for name in names:
  model = joblib.load('./{}_model.pkl'.format(name))
  evaluate_model(name,model,tst_features,tst_labels)