# -*- coding: utf-8 -*-
"""LR_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1giHmuF-brHlcTdnHp0DkLnF4Yj-kmxsR

## Logistic Regression: Fit and evaluate a model

Using the Heart dataset
"""

from time import time
from sklearn.metrics import accuracy_score , precision_score , recall_score

import joblib
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=DeprecationWarning)

data = np.loadtxt('./rand_heart.data',delimiter=',')
train = data[:,:-1]
label = data[:,-1]

scaler = preprocessing.StandardScaler().fit(train)
train = scaler.transform(train)

tr_features,tst_features = np.split(train,[int(len(train)*0.8)])
tr_labels,tst_labels = np.split(label,[int(len(label)*0.8)])

"""### Hyperparameter tuning


"""

def print_results(results):
    print('BEST PARAMS: {}\n'.format(results.best_params_))

    means = results.cv_results_['mean_test_score']
    stds = results.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, results.cv_results_['params']):
        print('{} (+/-{}) for {}'.format(round(mean, 3), round(std * 2, 3), params))

LogisticRegression()

lr = LogisticRegression()
parameters = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
}

cv = GridSearchCV(lr, parameters, cv=5)
cv.fit(tr_features, tr_labels)

print_results(cv)

cv.best_estimator_

"""### Write out pickled model"""

joblib.dump(cv.best_estimator_, './LR_model.pkl')

#Testing
model = joblib.load('./LR_model.pkl')

def evaluate_model(name,model,features,labels):
  start = time()
  pred = model.predict(features)
  end = time()

  accuracy = round(accuracy_score(labels,pred),3)
  precision = round(precision_score(labels,pred),3)
  recall = round(recall_score(labels,pred),3)
  print("{}-- accuracy: {} / precision: {} / recall: {}/ Latency: {} ".format(name,accuracy,precision,recall,round((end-start))))

evaluate_model('LR',model,tst_features,tst_labels)